### ISSUE TITLE
Magnetometer

### ISSUE THREAD

**Issue by hespanha** [KZSLAB/BMI160_Arduino_Library#1]
Are you able to make the magnetometer work? I have the BMI160/BMM150 Shuttle Board and I cannot get data from the magnetometer.

**Comment by uzhul38** [comment]
Still working on it ! Right know it is not functionnal but since the last time i understood that my initialization was not good. which led to getting nothing from the BMM150. Now i have something but there is some issues with the data.

If you have any idea or correction feel free to help !

**Comment by hespanha** [comment]
I went through the code in Bosch's device driver and tried to implement the initialization as closely to that as possible, but I am still not getting anything from the BMM (any read from any register of the BMM gets zero). However, I did see that they use lots of delays (ranging between 1-3ms) and also retry a few commands a few times. I implemented them as closely as possible, but still nothing.

You say that now you are getting something from the BMM150 -- does the code currently on github get any response from the BMM150?

**Comment by uzhul38** [comment]
There is a response at the first loop but after it, it goes crazy and i get -1 on all mag axes... i got 255 on the STATUS register tho. Could you send me a copy of your initialization to compare with mine ?
Thanks.

**Comment by hespanha** [comment]
Here goes the code I used. The prints refer to commands in the Bosch device driver. The function
     bmi160->write8(address,value) -- writes a value to a bmi160 register
     bmi160->read8(address) -- read a value to a bmi160 register
Hope this helps.

`  Serial.println("  Configuring BMM150 (Bosch)");
  Serial.println("     bmi160_set_command_register(ACCEL_MODE_NORMAL);");
  bmi160->write8(0x7E,0x11);
  delay(5);
  Serial.println("     bmi160_set_mag_interface_normal();");
  delay(1);
  bmi160->write8(0x7E,0x19);
  delay(1);
  Serial.print  ("       BMI160_USER_MAG_POWER_MODE_STAT__REG (bits 10 == 1?)=0b");
  Serial.println((uint8_t)bmi160->read8(0x03),BIN);
  delay(1);
  Serial.println("     bmi160_set_i2c_device_addr(BMI160_AUX_BMM150_I2C_ADDRESS);");
  Serial.print  ("       BMI160_USER_I2C_DEVICE_ADDR__REG (will set bits 7-1)=0b");
  uint8_t rc=bmi160->read8(0x4B);
  delay(1);
  Serial.println((uint8_t)rc,BIN);
  bmi160->write8(0x4B,rc+0x20);
  delay(1);
  delay(1);
  Serial.println("     bmi160_set_mag_manual_enable(BMI160_MANUAL_ENABLE);");
  bmi160->write8(0x4C,0b10000000);
  delay(1);
  Serial.println("     bmi160_get_mag_manual_enable(&v_data_u8);");
  Serial.print  ("       BMI160_USER_MAG_MANUAL_ENABLE__REG (bit 7)=0b");
  Serial.println((uint8_t)bmi160->read8(0x4C),BIN);
  Serial.println("     bmi160_set_if_mode(BMI160_ENABLE_MAG_IF_MODE);");
  Serial.print  ("       BMI160_USER_IF_CONFIG_IF_MODE__RE (bit 54 | 0b10)=0b");
  rc=bmi160->read8(0x6B);
  Serial.print((uint8_t)rc,BIN);
  rc = rc | 0b100000;
  Serial.print("->0x");
  Serial.println((uint8_t)rc,BIN);
  bmi160->write8(0x6B,rc);
  delay(1);
  Serial.println("     bmi160_get_if_mode();");
  Serial.print  ("       BMI160_USER_IF_CONFIG_IF_MODE__RE (bit 54)=0b");
  rc=bmi160->read8(0x6B);
  Serial.println((uint8_t)rc,BIN);
  Serial.println("     bmi160_bmm150_mag_wakeup();");
  Serial.println("      while(5 times){\n");
  for (int q=0;q<5;q++) {
    Serial.println("        bmi160_set_mag_write_data(BMI160_BMM150_POWER_ON);");
    bmi160->write8(0x4F,0x01);
    delay(2);
    /*write 0x4B register to enable power control bit*/
    Serial.println("        bmi160_set_mag_write_addr(BMI160_BMM150_POWER_CONTROL_REG);");
    bmi160->write8(0x4E,0x4B);
    delay(1);
    delay(3);
    Serial.println("        bmi160_set_mag_read_addr(BMI160_BMM150_POWER_CONTROL_REG);");
    bmi160->write8(0x4D,0x4B);
    delay(1);
    /* 0x04 is secondary read Mag x LSB register */
    delay(1);
    Serial.print("        BMI160_USER_DATA_0_ADDR (bit0==1)?=0b");
    rc=bmi160->read8(0x04);
    Serial.println((uint8_t)rc,BIN);
    delay(1);

    if ((rc & 1) ==0) {
      Serial.println("        BAD!!! - MAG not powered!");
    }
  }
  Serial.println("      }\n");

  Serial.println("        bmi160_set_mag_read_addr(BMI160_BMM150_CHIP_ID);");
  bmi160->write8(0x4E,0x40);
  delay(1);
  delay(1);
  Serial.print("        BMI160_MAG_DATA_READ_REG =0b");
  rc=bmi160->read8(0x04);
  Serial.println((uint8_t)rc,BIN);
  delay(5);
`

**Comment by uzhul38** [comment]
hum, i feel like you missed some points in the initialisation. You didn't do the part in the BMI160_BMM150_POWER_MODE_REG plus you didn't setup the repetitions for the X, Y and Z axis of the magnetometer. At the end of the init, you have to put the BMM150 in FORCED Mode, set the output data rate at 25Hz, set the read address at 0x42 and finally disable the Manual mode.

**Comment by uzhul38** [comment]
Hello, the library is now working with the BMM150 as second interface !
